---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-monitor-controller
  namespace: devops
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: ingress-monior-controller
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: ingressmonitorcontroller
    version: 1.0.98
  values:
    nameOverride: "ingress-monitor-controller"
    ingressMonitorController:
      tolerations: {}
      watchNamespace: ""
      mount: "secret"
      existingSecret: "ingress-monitor-controller-secret"
      useFullName: false
      logLevel: error
      logFormat: text
      image:
        name: dieunb/ingressmonitorcontroller
        tag: "dev2"
        pullPolicy: IfNotPresent
      configFilePath: /etc/IngressMonitorController/config.yaml
      data: {}
