# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("jobs.proto", :syntax => :proto3) do
    add_message "rpc.GetJobReq" do
      optional :id, :uint64, 1
    end
    add_message "rpc.GetJobResp" do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
  end
end

module Rpc
  GetJobReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetJobReq").msgclass
  GetJobResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetJobResp").msgclass
end
