---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: prometheus-ki
  namespace: devops
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
proxy:
  path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: devops
  annotations:
    konghq.com/override: prometheus-ki
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: server.prometheus.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-server
            servicePort: 80
    - host: alertmanager.prometheus.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-alertmanager
            servicePort: 80
    - host: kube-state-metrics.prometheus.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-kube-state-metrics
            servicePort: 8080
    - host: pushgateway.prometheus.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-pushgateway
            servicePort: 9091
    - host: node-exporter.prometheus.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-node-exporter
            servicePort: 9100
