---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:dieunb/app-infra.git
    path: charts/mokey
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.2.3
    replicaCount: 1
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
