---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo-dev
  chart:
    git: https://github.com/dieunb/app-infra.git
    path: charts/mokey
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.2.3
    replicaCount: 1
