---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-api-ingress
  namespace: application
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: sbx-mobile-mobile-force-update
spec:
  rules:
    - host: api.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: web-service
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: application
  labels:
    app: web-service
spec:
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: application
  labels:
    app: web-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: api
        image: dieunb/test_kong_service:latest
        imagePullPolicy: "IfNotPresent"
        command: ["bundle", "exec", "puma", "-p", "80", "-C", "config/puma.rb"]
        ports:
          - containerPort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: sbx-mobile-mobile-force-update
  namespace: application
config:
  blacklist:
    - path: "test-deprecated-route-1"
      version_range: []
    - path: "test-deprecated-route-2"
      version_range:
      - 0.0.0
      - 1.0.0
plugin: mobile-force-update
