version: "3.5"

services:
  postgres:
    image: postgres:9.6.11-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432"

  kong-db-bootstrap:
    build: .
    command: 'kong migrations bootstrap'
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - postgres

  kong:
    build: .
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /usr/local/kong
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_DATABASE: postgres
      KONG_GO_PLUGINS_DIR: /usr/local/go-plugins
      KONG_PLUGINS: bundled,hello-plugin
      KONG_LOG_LEVEL: debug
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_HEADERS: "off"
    restart: on-failure
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - postgres
      - kong-db-bootstrap

  # Konga is a Kong UI
  # https://github.com/pantsel/konga
  konga:
    image: pantsel/konga:next
    restart: always
    environment:
      NODE_ENV: production
      NO_AUTH: "true"
    ports:
      - "1337:1337"
