apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-magic
  namespace: devops
  labels:
    app: kafka-magic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-magic
  template:
    metadata:
      labels:
        app: kafka-magic
    spec:
      containers:
      - name: kafka-magic
        image: digitsy/kafka-magic
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-magic-web
  namespace: devops
  annotations:
    konghq.com/override: kafka-magic-ki
spec:
  type: ClusterIP
  selector:
    app: kafka-magic
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kafka-magic-ki
  namespace: devops
upstream:
  host_header: google.com
proxy:
  protocol: http
  path: /
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafka-magic-ig
  namespace: devops
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: "/kafka-magic"
            backend:
              serviceName: kafka-magic-web
              servicePort: 8080
