---
apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: application
  labels:
    app: clamav
spec:
  selector:
    app: clamav
  ports:
  - name: zombie-port # Actually, we do not use this port but it is still needed to allow the service to receive TCP traffic.
    port: 1234
    targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: application
  labels:
    name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - name: clamd
        image: quay.io/ukhomeofficedigital/clamav:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3310
          name: api
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 90
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 10
      - name: scanner
        image: dieunb/virus-scan:0.0.2
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
