apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: application
  labels:
    name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - name: clamd
        image: quay.io/ukhomeofficedigital/clamav:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3310
          name: api
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 90
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
