apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: application
  labels:
    name: clamav
spec:
  replicas: 1
  selector:
    name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - name: clamd
        image: quay.io/ukhomeofficedigital/clamav:latest
        env:
        - name: UPDATE
          value: "false"
        ports:
        - containerPort: 3200
          name: api
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2
      - name: freshclam
        image: quay.io/ukhomeofficedigital/clamav:latest
        env:
        - name: UPDATE_ONLY
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2
      volumes:
      - name: avdata
        source:
          emptyDir: {}
