---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-training-ingress
  namespace: application
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: go-api.internal.local
      http:
        paths:
        - path: /
          backend:
            serviceName: go-training
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-training
  namespace: application
  labels:
    app: go-training
spec:
  selector:
    app: go-training
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-training
  namespace: application
  labels:
    app: go-training
spec:
  replicas: 0
  selector:
    matchLabels:
      app: go-training
  template:
    metadata:
      labels:
        app: go-training
    spec:
      containers:
      - name: web
        image: dieunb/go-training:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8080

