apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: load-tester
  namespace: devops
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: load-tester
  chart:
    repository: https://flagger.app
    name: 0.16.0
    version: flagger/loadtester
  values:
    fullnameOverride: load-tester
