---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: devops
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:dieunb/app-infra.git
    ref: master
    path: charts/podinfo
  values:
    replicaCount: 0
    image:
      repository: stefanprodan/podinfo
      tag: multiarch
    service:
      enabled: true
      type: ClusterIP

