---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: devops
  annotations:
    flux.weave.works/automated: "true"
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:dieunb/app-infra.git
    ref: master
    path: charts/podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.5
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kong
      path: /podinfo
