---
# Pomerium is a Oauth2 proxy to authenticate our internal services
#
# To place your service pomerium:
# - Copy an item in the spec.values.config.policy below
# - Update *from* and *to* value to the domain of your service
#
# *from* is the external domain that users connect to
# *to* is the K8S service in the form:
# <service name>.<namespace>.svc.cluster.local:<service port>
#
# Notice that you don't have to create an Ingress object on your own
# Pomerium already takes care of that for you.

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: devops
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: pomerium
  helmVersion: v3
  chart:
    repository: https://helm.pomerium.io
    name: pomerium
    version: 5.0.2
  valuesFrom:
  - secretKeyRef:
      name: pomerium-secret
      key: values.yaml
  values:
    extraEnv:
      LOG_LEVEL: error
      CACHE_STORE: bolt
      CACHE_STORE_PATH: /etc/bolt.db

    config:
      rootDomain: "internal.local"

      policy:
        - from: https://prometheus.internal.local
          to: http://prometheus.devops.svc.cluster.local:9200
          allowed_domains:
            - "*"
          cors_allow_preflight: true
          timeout: 60s

    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      secret:
        name: pomerium-tls
        cert: ""
        key: ""
