---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: podinfo-cors
  namespace: devops
config:
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  headers:
    - Authorization
    - Jwt-Token
    - Content-Type
  origins:
    - "*"
  credentials: true
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: podinfo-basic-auth
  namespace: devops
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-consumer-secret
  namespace: devops
type: Opaque
data:
  kongCredType: YmFzaWMtYXV0aA==
  username: YmFzaWMtYXV0aA==
  password: YmFzaWMtYXV0aA==
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: devops-consumer
  namespace: devops
username: devops
credentials:
  - devops-consumer-secret
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: podinfo-ki
  namespace: devops
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  # https://docs.konghq.com/2.1.x/health-checks-circuit-breakers/
  healthchecks:
    # This service has 24 web instances <=> 24 targets
    # by default all target is same weight, that is 100.
    # Threshold value means that Kong will respond to requests to the upstream with 503 Service Unavailable
    # when number of healthy targets < 2.4 (10 * 24 / 100)
    threshold: 10
    active:
      concurrency: 18
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 30
        successes: 1
      http_path: "/health"
      timeout: 30
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 502
        - 503
        interval: 15
        tcp_failures: 0
        timeouts: 30
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 1
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 502
        - 503
        tcp_failures: 0
        timeouts: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: podinfo-ki
    konghq.com/plugins: podinfo-cors,podinfo-basic-auth
    monitor.stakater.com/enabled: "true"
    monitor.stakater.com/healthEndpoint: "/"
    monitor.stakater.com/overridePath: "/healthz"
    monitor.stakater.com/name: "Pod info"
    monitor.stakater.com/forceHttps: "true"
#    appinsights.monitor.stakater.com/statuscode: "200"
#    appinsights.monitor.stakater.com/retryenable: "false"
#    appinsights.monitor.stakater.com/frequency: "900"
spec:
  rules:
    - host: medium.com
      http:
        paths:
        - path: /podinfo
          backend:
            serviceName: podinfo
            servicePort: 8989
