---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops
data:
  debezium-pg-credentials.properties: cGdfdXNlcm5hbWU6IHJlcGxpY2F0b3IKcGdfcGFzc3dvcmQ6IHNUbWJmUDk1dGE4RnNSQ3QyUHdjVWZNRwo=
  #cGdfdXNlcm5hbWU6IGtvbmcKcGdfcGFzc3dvcmQ6IGtvbmcK
