---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: kong-connector-source
  namespace: devops
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  pause: false
  config:
    database.hostname: "postgres-postgresql.stateful.svc.cluster.local"
    database.port: "5432"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/debezium-pg-credentials.properties:pg_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/debezium-pg-credentials.properties:pg_password}"
    database.dbname: "kong_gateway"
    database.server.name: "development"
    database.history.kafka.bootstrap.servers: "kafka-0.kafka-headless.stateful.svc.cluster.local:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    include.schema.changes: "true"
    slot.name: "kong_gateway_source_pg_connector"
    tasks.max: "1"
    plugin.name: "pgoutput"
    table.whitelist: "public.services"
    key.converter.schemas.enable: "true"
    value.converter.schemas.enable: "true"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
