# kubectl create deployment postgres-client --image=tmaier/postgresql-client:latest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
      - name: kafka-client
        image: dieunb/kafka-client:2.5.0
        command:
          - sleep
          - "3600"
