---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: debeziumconnectors.configuration.eh.com
spec:
  group: configuration.eh.com
  version: v1
  scope: Namespaced
  names:
    kind: DebeziumConnector
    plural: debeziumconnectors
    shortNames:
    - dc
  additionalPrinterColumns:
  - name: Connector-Type
    type: string
    description: Name of the connector
    JSONPath: .connector
  - name: Age
    type: date
    description: Age
    JSONPath: .metadata.creationTimestamp
  - name: Disabled
    type: boolean
    description: Indicates if the connector is disabled
    JSONPath: .disabled
    priority: 1
  - name: Config
    type: string
    description: Configuration of the connector
    JSONPath: .config
    priority: 1
  validation:
    openAPIV3Schema:
      required:
      - connector
      properties:
        connector:
          type: string
        disabled:
          type: boolean
        config:
          type: object
        configFrom:
          type: object
          properties:
            secretKeyRef:
              required:
              - name
              - key
              type: object
              properties:
                name:
                  type: string
                key:
                  type: string
