---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: demo-cors
  namespace: default
config:
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  headers:
    - Authorization
    - Jwt-Token
    - Content-Type
  origins:
    - "*"
  credentials: true
plugin: cors
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  namespace: default
  annotations:
    konghq.com/plugins: demo-cors
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: echo
          servicePort: 80
