---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: konga-ingress
  namespace: devops
  labels:
    app: konga
spec:
  rules:
    - host: konga.kubernetes.internal
      http:
        paths:
        - path: /
          backend:
            serviceName: konga
            servicePort: 80
