---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-proxy
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: api-proxy-custom
    konghq.com/plugins: api-proxy-rate-limiting
    konghq.com/path: "/open_api/v1"
    konghq.com/protocol: https
  labels:
    app: echo
spec:
  rules:
    - host: api.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
    - host: openapi.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: api-proxy-custom
  namespace: default
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
---
 apiVersion: configuration.konghq.com/v1
 kind: KongPlugin
 metadata:
   name: api-proxy-rate-limiting
   namespace: dev
 config:
   redis_database: 0
   policy: "cluster"
   redis_timeout: 2000
   hide_client_headers: false
   hour: 2000
   minute: 100
   limit_by: "ip"
   redis_port: 6379
   second: 10
   fault_tolerant: true
 plugin: rate-limiting
