---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-proxy
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: api-proxy-custom
  labels:
    app: demo
spec:
  rules:
    - host: api.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
    - host: openapi.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: api-proxy-custom
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  healthchecks:
    threshold: 25
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 0
      http_path: "/"
      timeout: 1
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        interval: 0
        tcp_failures: 0
        timeouts: 0
    passive:
      healthy:
        http_statuses:
        - 200
        successes: 0
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 503
        tcp_failures: 0
        timeouts: 0
proxy:
  protocol: http
  path: /open_api/v1
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
