---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-proxy
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    app: demo
spec:
  rules:
    - host: api.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
    - host: openapi.demo.local.internal
      http:
        paths:
          - path: "/api/v1"
            backend:
              serviceName: echo
              servicePort: 80
