---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: podinfo-cors
  namespace: devops
config:
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  headers:
    - Authorization
    - Jwt-Token
    - Content-Type
  origins:
    - "*"
  credentials: true
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: podinfo-basic-auth
  namespace: devops
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-consumer-secret
  namespace: devops
type: Opaque
data:
  kongCredType: YmFzaWMtYXV0aA==
  username: YmFzaWMtYXV0aA==
  password: YmFzaWMtYXV0aA==
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: devops-consumer
  namespace: devops
username: devops
credentials:
  - devops-consumer-secret
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: podinfo-ki
  namespace: devops
upstream:
  host_header: "podinfo.internal.local"
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: podinfo-ki
    konghq.com/plugins: podinfo-cors,podinfo-basic-auth
    monitor.stakater.com/enabled: "true"
#    monitor.stakater.com/healthEndpoint: "/api/status"
#    monitor.stakater.com/name: "Pod info"
#    monitor.stakater.com/forceHttps: "true"
#    appinsights.monitor.stakater.com/statuscode: "200"
#    appinsights.monitor.stakater.com/retryenable: "false"
#    appinsights.monitor.stakater.com/frequency: "900"
spec:
  rules:
    - host: medium.com
      http:
        paths:
        - path: /podinfo
          backend:
            serviceName: podinfo
            servicePort: 8989
