---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: podinfo-cors
  namespace: devops
config:
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  headers:
    - Authorization
    - Jwt-Token
    - Content-Type
  origins:
    - "*"
  credentials: true
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: podinfo-ki
  namespace: devops
upstream:
  host_header: "podinfo.internal.local"
route:
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - OPTION
    - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
  protocols:
    - http
    - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: podinfo-ki
    konghq.com/plugins: podinfo-cors
spec:
  rules:
  - http:
      paths:
      - path: /podinfo
        backend:
          serviceName: podinfo
          servicePort: 8989
