# create database kong_gateway;
# create user kong_gateway with encrypted password 'kong_gateway';
# grant all privileges on database kong_gateway to kong_gateway;
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: devops
data:
  KONG_PG_HOST: cG9zdGdyZXMtcG9zdGdyZXNxbC5zdGF0ZWZ1bC5zdmMuY2x1c3Rlci5sb2NhbAo=
  KONG_PG_USER: a29uZ19nYXRld2F5Cg==
  KONG_PG_PASSWORD: a29uZ19nYXRld2F5Cg==
  KONG_PG_DATABASE: a29uZ19nYXRld2F5Cg==
