apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: devops
data:
  KONG_PG_HOST: cG9zdGdyZXMtcG9zdGdyZXNxbC5zdGF0ZWZ1bC5zdmMuY2x1c3Rlci5sb2NhbAo=
  KONG_PG_USER: a29uZwo=
  KONG_PG_PASSWORD: a29uZwo=
  KONG_PG_DATABASE: a29uZwo=
