apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: devops
data:
  KONG_PG_HOST: cG9zdGdyZXMtcG9zdGdyZXNxbC5kZXZvcHMuc3ZjLmNsdXN0ZXIubG9jYWwK
  KONG_PG_USER: a29uZwo=
  KONG_PG_PASSWORD: a29uZwo=
  KONG_PG_DATABASE: a29uZwo=
